"""
Decode matrix test for bslz4_to_sparse -- works on Python 2.7 and 3.x.

It reads a small pre-generated fixture (test/matrix.h5 + test/matrix.json,
both gitignored, produced by ``python3 test/make_testcases.py matrix``) and
decodes each chunk by raw (byte offset, length) from the index.  It never
hands a compressed chunk to h5py: on Python 2.7 the last supporting h5py
(2.10) has no get_chunk_info and read_direct_chunk returns an array()
string repr (garbage).  This file therefore runs identically on 2.7 and 3.x.

Fixtures may be missing (e.g. a py2.7-only job); then the test skips.  The
fixture is generated by a Python 3.x step beforehand.
"""

from __future__ import print_function

import json
import os
import sys

_path = os.environ.get("BSLZ4_TO_SPARSE_PATH")
if _path:
    sys.path.insert(0, _path)

import numpy as np
import pytest

from bslz4_to_sparse import chunk2sparse

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_PATH = os.path.join(REPO_ROOT, "test", "matrix.json")
H5_PATH = os.path.join(REPO_ROOT, "test", "matrix.h5")

_DTYPES = {
    "u8": np.uint8, "u16": np.uint16, "u32": np.uint32, "u64": np.uint64,
    "i8": np.int8, "i16": np.int16, "i32": np.int32, "i64": np.int64,
    "f32": np.float32, "f64": np.float64,
}


def _load_index():
    if not (os.path.exists(INDEX_PATH) and os.path.exists(H5_PATH)):
        return None
    with open(INDEX_PATH, "r") as fp:
        return json.load(fp)


_INDEX = _load_index()

if _INDEX is None:
    def test_missing_decode_matrix_fixture():
        pytest.skip(
            "decode matrix fixture absent; run: python3 test/make_testcases.py matrix")
else:
    _ENTRIES = _INDEX["chunks"]

    @pytest.mark.parametrize("entry", _ENTRIES, ids=lambda e: e["name"])
    def test_decode_matrix_chunk(entry):
        with open(H5_PATH, "rb") as fh:
            fh.seek(entry["offset"])
            chunk = fh.read(entry["length"])
        assert len(chunk) == entry["length"], "short read"

        dtype = _DTYPES[entry["dtype"]]
        cut = entry["cut"]
        rows = entry["rows"]
        cols = entry["cols"]
        codec = entry["codec"]

        mask = np.ones((rows, cols), np.uint8)
        c2s = chunk2sparse(mask, dtype=dtype, codec=codec)
        npx, (vals, adrs) = c2s(chunk, cut)

        got = {}
        for k in range(npx):
            got[int(adrs[k])] = vals[k].item()
        expected = dict((int(i), v) for i, v in entry["nonzero"])

        assert npx == len(expected), (entry["name"], npx, len(expected))
        assert got == expected, (entry["name"], got, expected)
