#!/usr/bin/env python3
"""Generate the documentation pages from the code, by running it.

Every page under docs/gen/ is written here and nowhere else (docs/gen/ is
git-ignored; see docs/AGENTS.md):

  docs/gen/examples/<name>.md  each examples/ex*.py: its docstring, its source,
                               and the output of running it now
  docs/gen/api.md              the docstrings and signatures of the public API,
                               and the decode error codes, read from the module
  docs/gen/pipelines.md        every pipeline step value and what it needs,
                               from src/_pipeline.py
  docs/gen/performance.md      docs/bench/real_data.json (measured on a real
                               machine by tools/bench_docs.py, never here)

An example that raises or exits non-zero stops the build: the site cannot
show an example that does not run.  The bslz4_to_sparse that is imported
(the installed wheel in CI, or BSLZ4_TO_SPARSE_PATH) is the one documented.

    BSLZ4_TO_SPARSE_PATH=lib python3 tools/generate_docs.py
    mkdocs build --strict -f docs/mkdocs.yml
"""
import glob
import inspect
import json
import os
import subprocess
import sys
import textwrap

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")
GEN = os.path.join(DOCS, "gen")
BENCH = os.path.join(DOCS, "bench", "real_data.json")
_path = os.environ.get("BSLZ4_TO_SPARSE_PATH")
if _path:
    sys.path.insert(0, _path)

import bslz4_to_sparse as b  # noqa: E402
from bslz4_to_sparse import _pipeline  # noqa: E402

GITHUB = "https://github.com/jonwright/bslz4_to_sparse"


def examples():
    return sorted(glob.glob(os.path.join(REPO, "examples", "ex*.py")))


def provenance():
    info = b.build_info()
    return ("<small>Generated by `tools/generate_docs.py` from bslz4_to_sparse %s "
            "(git `%s`, sources sha256 `%s`).</small>\n"
            % (b.version, info["git"], info["src_sha256"][:12]))


def write(rel, text):
    path = os.path.join(GEN, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(path, REPO))


def fence(lang, body):
    return "```%s\n%s\n```\n" % (lang, body.rstrip("\n"))


# ---------------------------------------------------------------- examples

def run_example(path):
    """stdout of running the example as a user would, in an empty directory."""
    env = dict(os.environ)
    pkg_parent = os.path.dirname(os.path.dirname(os.path.abspath(b.__file__)))
    env["PYTHONPATH"] = os.pathsep.join([pkg_parent] + [p for p in [env.get("PYTHONPATH")] if p])
    r = subprocess.run([sys.executable, path], env=env, cwd=os.path.dirname(path),
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if r.returncode != 0:
        raise SystemExit("example %s failed (exit %d):\n%s%s"
                         % (os.path.relpath(path, REPO), r.returncode,
                            r.stdout.decode(), r.stderr.decode()))
    return r.stdout.decode()


def split_docstring(source):
    """(title, body, code) of an example: its module docstring and the rest."""
    mod = compile(source, "<example>", "exec", 0x400)          # PyCF_ONLY_AST
    doc = inspect.cleandoc(mod.body[0].value.value)
    title, _, body = doc.partition("\n")
    end = mod.body[1].lineno - 1 if len(mod.body) > 1 else len(source.splitlines())
    code = "\n".join(source.splitlines()[end:]).strip("\n")
    return title.strip().rstrip("."), body.strip(), code


def example_page(path):
    with open(path) as fh:
        source = fh.read()
    title, body, code = split_docstring(source)
    out = run_example(path)
    rel = os.path.relpath(path, REPO)
    return title, (
        "# %s\n\n%s\n\n" % (title, body)
        + "Source: [`%s`](%s/blob/main/%s), run as `python %s`.\n\n" % (rel, GITHUB, rel, rel)
        + fence("python", code)
        + "\nOutput, from running it when this page was built:\n\n"
        + fence("text", out)
        + "\n" + provenance())


# ---------------------------------------------------------------- API

PUBLIC_CLASSES = ("chunk2sparse", "chunk2sparseCSC")
PUBLIC_METHODS = ("__call__", "multi", "decode_offsets", "coo")


def signature(obj, name):
    try:
        return "%s%s" % (name, inspect.signature(obj))
    except (TypeError, ValueError):
        return name


def docblock(obj):
    doc = inspect.getdoc(obj)
    if not doc:
        raise SystemExit("%r has no docstring: write one in the code, not here"
                         % getattr(obj, "__qualname__", obj))
    return fence("text", doc)


def api_page():
    parts = ["# API reference\n",
             "Everything here is read from the installed module: the signatures by "
             "introspection, the text from the docstrings in `src/`.\n",
             "## The package\n", fence("text", inspect.getdoc(b))]
    for name in PUBLIC_CLASSES:
        cls = getattr(b, name)
        parts.append("## %s\n" % name)
        parts.append(fence("python", "class " + signature(cls, name)))
        parts.append(docblock(cls))
        for m in PUBLIC_METHODS:
            meth = getattr(cls, m)
            parts.append("### %s.%s\n" % (name, m))
            parts.append(fence("python", signature(meth, m)))
            parts.append(docblock(meth))
    funcs = [n for n in b.__all__ if n not in PUBLIC_CLASSES and callable(getattr(b, n))]
    for name in funcs:
        fn = getattr(b, name)
        parts.append("## %s\n" % name)
        parts.append(fence("python", signature(fn, name)))
        parts.append(docblock(fn))
    consts = [n for n in b.__all__ if not callable(getattr(b, n))]
    parts.append("## Constants\n")
    parts.append("| name | value |\n|---|---|\n"
                 + "".join("| `%s` | `%r` |\n" % (n, getattr(b, n)) for n in consts))
    parts.append("\n## Decode errors\n\nA negative return from the native decode is "
                 "raised as an `Exception` with this text (`_DECODE_ERRORS` in "
                 "`src/__init__.py`):\n\n| code | meaning |\n|---|---|\n"
                 + "".join("| %d | %s |\n" % (k, v) for k, v in sorted(b._DECODE_ERRORS.items(),
                                                                        reverse=True)))
    parts.append("\n" + provenance())
    return "\n".join(parts)


# ---------------------------------------------------------------- pipelines

def pipelines_page():
    parts = ["# Pipeline steps and values\n",
             "Every value of every step, with what it needs, from `VALUES` in "
             "`src/_pipeline.py`.  Value 0 (`auto`) is resolved when an object is "
             "made; `describe()` shows which values the running machine can use "
             "(see the [pipelines example](examples/ex4_pipelines.md)).\n"]
    for step in _pipeline.STEPS:
        parts.append("## %s\n" % step)
        parts.append("| value | name | needs / does |\n|---|---|---|\n"
                     + "".join("| %d | `%s` | %s |\n" % (i, v[0], v[1])
                               for i, v in enumerate(_pipeline.VALUES[step]) if i))
    parts.append("\n" + provenance())
    return "\n".join(parts)


# ---------------------------------------------------------------- performance

def bench_docs_py_sha256():
    """The hash tools/bench_docs.py records, of the module being documented."""
    sys.path.insert(0, os.path.join(REPO, "tools"))
    try:
        from bench_docs_hash import py_sha256
    finally:
        sys.path.pop(0)
    return py_sha256(os.path.dirname(b.__file__))


def pct(frac):
    """A fraction as a percentage: two significant figures, whole numbers from 10 %."""
    p = 100 * frac
    return ("%.0f %%" % p) if p >= 10 else ("%.2g %%" % p)


def performance_page():
    with open(BENCH) as fh:
        bench = json.load(fh)
    m, meth = bench["machine"], bench["method"]
    here = b.build_info()["src_sha256"]
    here_py = bench_docs_py_sha256()
    parts = ["# Performance on real data\n"]
    if m["src_sha256"] != here or m.get("py_sha256") != here_py:
        parts.append('!!! warning "Measured on older code"\n'
                     "    These numbers were measured at git `%s` (C sources sha256 `%s`, "
                     "kernel-choice modules `%s`); this site was built from `%s` / `%s`.  "
                     "The code changed since, so they may no longer describe it.  Re-run "
                     "`tools/bench_docs.py` and commit `docs/bench/real_data.json`.\n"
                     % (m["git"], m["src_sha256"][:12], str(m.get("py_sha256"))[:12],
                        here[:12], here_py[:12]))
    parts.append(
        "Measured on **%s**, %d core usable, %s UTC, with bslz4_to_sparse %s (git `%s`, "
        "sources sha256 `%s`), %s, Python %s, numpy %s, pyFAI %s.\n"
        % (m["cpu"], m["cores_usable"], bench["date_utc"], m["version"], m["git"],
           m["src_sha256"][:12], m["compiler"], m["python"], m["numpy"], m["pyFAI"]))
    parts.append(
        "%d frames spread over each file were read into memory first (no file I/O "
        "is timed), then decoded in batches of %d after one warmup batch; the best "
        "of %d passes is shown.  GB = 10^9 bytes.  *Compressed* GB/s counts the "
        "bitshuffle-LZ4 bytes consumed, *pixels* GB/s the decompressed frame "
        "(pixels x bytes per pixel): their ratio is the compression ratio.  "
        "Pipelines are the automatic choice.\n"
        % (meth["frames"], meth["batch"], meth["repeats"]))
    g = meth["geometry"]
    parts.append(
        "The files carry no calibration, so the matrices use one generic geometry for "
        "every case: %g um pixels, %g m distance, beam at the detector centre, "
        "wavelength %g m, no tilts.  They set the size and shape of the work, not a "
        "fit to these samples.  Masked pixels: %s.\n"
        % (g["pixel_m"] * 1e6, g["dist_m"], g["wavelength_m"], meth["mask"]))
    op_order = []                                   # as measured (the JSON keys are sorted)
    for r in bench["results"]:
        if r["op"] not in op_order:
            op_order.append(r["op"])
    parts.append("## Operations\n\n| operation | what is timed |\n|---|---|\n"
                 + "".join("| %s | %s |\n" % (op, bench["ops"][op]) for op in op_order))
    for case in bench["cases"]:
        rows = [r for r in bench["results"] if r["case"] == case["key"]]
        parts.append("## %s: %s\n" % (case["key"], case["label"]))
        parts.append("`%s`, dataset `%s`: %d frames of %s %s; compression %.1f; "
                     "%d masked pixels.  Sparse cut %d: %s of the unmasked pixels are "
                     "above it and go to the sparse output (mean over the timed frames).\n"
                     % (case["file"], case["dataset"], case["frames_in_file"],
                        " x ".join(str(s) for s in case["shape"]), case["dtype"],
                        case["compression"], case["masked_pixels"], case["cut"],
                        pct(case["kept_frac"])))
        parts.append("| operation | frames/s | compressed GB/s | pixels GB/s |\n"
                     "|---|---:|---:|---:|\n"
                     + "".join("| %s | %.1f | %.3f | %.2f |\n"
                               % (r["op"], r["fps"], r["compressed_gbs"], r["pixel_gbs"])
                               for r in rows))
        mats = [r for r in rows if r["matrix"]]
        if mats:
            parts.append("\n| matrix | bins | entries | pixels with an entry |\n"
                         "|---|---:|---:|---:|\n"
                         + "".join("| %s | %s | %d | %s |\n"
                                   % (r["op"], " x ".join(str(n) for n in r["matrix"]["bins_shape"]),
                                      r["matrix"]["nnz"], pct(r["matrix"]["pixel_frac"]))
                                   for r in mats))
    parts.append("\nSource: [`docs/bench/real_data.json`](%s/blob/main/docs/bench/real_data.json), "
                 "written by `%s`.\n\n" % (GITHUB, bench["tool"]) + provenance())
    return "\n".join(parts)


def main():
    write("api.md", api_page())
    write("pipelines.md", pipelines_page())
    write("performance.md", performance_page())
    for path in examples():
        name = os.path.splitext(os.path.basename(path))[0]
        _title, page = example_page(path)
        write(os.path.join("examples", name + ".md"), page)


if __name__ == "__main__":
    main()
