#!/usr/bin/env python3
"""Generate the documentation pages from the code, by running it.

Every page under docs/gen/ is written here and nowhere else (docs/gen/ is
git-ignored; see docs/AGENTS.md):

  docs/gen/examples/<name>.md  each examples/ex*.py: its docstring, its source,
                               and the output of running it now
  docs/gen/api.md              the docstrings and signatures of the public API,
                               and the decode error codes, read from the module
  docs/gen/pipelines.md        every pipeline step value and what it needs,
                               from src/_pipeline.py
  docs/gen/acknowledgements.md the Acknowledgements and References of
                               README.md, and the licences in licenses/
  docs/gen/kernels.md          docs/bench/kernels_*.json: each pipeline step on
                               real data (tools/bench_kernels.py, never here)
  docs/gen/performance.md      docs/bench/real_data_*.json, one per machine
                               (measured there by tools/bench_docs.py, never here)

An example that raises or exits non-zero stops the build: the site cannot
show an example that does not run.  The bslz4_to_sparse that is imported
(the installed wheel in CI, or BSLZ4_TO_SPARSE_PATH) is the one documented.

    BSLZ4_TO_SPARSE_PATH=lib python3 tools/generate_docs.py
    mkdocs build --strict -f docs/mkdocs.yml
"""
import glob
import inspect
import json
import os
import re
import subprocess
import sys
import textwrap

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")
GEN = os.path.join(DOCS, "gen")
BENCH_GLOB = os.path.join(DOCS, "bench", "real_data_*.json")
_path = os.environ.get("BSLZ4_TO_SPARSE_PATH")
if _path:
    sys.path.insert(0, _path)

import bslz4_to_sparse as b  # noqa: E402
from bslz4_to_sparse import _pipeline  # noqa: E402

GITHUB = "https://github.com/jonwright/bslz4_to_sparse"


def examples():
    return sorted(glob.glob(os.path.join(REPO, "examples", "ex*.py")))


def provenance():
    info = b.build_info()
    return ("<small>Generated by `tools/generate_docs.py` from bslz4_to_sparse %s "
            "(git `%s`, sources sha256 `%s`).</small>\n"
            % (b.version, info["git"], info["src_sha256"][:12]))


def write(rel, text):
    path = os.path.join(GEN, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(path, REPO))


def fence(lang, body):
    return "```%s\n%s\n```\n" % (lang, body.rstrip("\n"))


# ---------------------------------------------------------------- examples

def run_example(path):
    """stdout of running the example as a user would, in an empty directory."""
    env = dict(os.environ)
    pkg_parent = os.path.dirname(os.path.dirname(os.path.abspath(b.__file__)))
    env["PYTHONPATH"] = os.pathsep.join([pkg_parent] + [p for p in [env.get("PYTHONPATH")] if p])
    r = subprocess.run([sys.executable, path], env=env, cwd=os.path.dirname(path),
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if r.returncode != 0:
        raise SystemExit("example %s failed (exit %d):\n%s%s"
                         % (os.path.relpath(path, REPO), r.returncode,
                            r.stdout.decode(), r.stderr.decode()))
    return r.stdout.decode()


def split_docstring(source):
    """(title, body, code) of an example: its module docstring and the rest."""
    mod = compile(source, "<example>", "exec", 0x400)          # PyCF_ONLY_AST
    doc = inspect.cleandoc(mod.body[0].value.value)
    title, _, body = doc.partition("\n")
    end = mod.body[1].lineno - 1 if len(mod.body) > 1 else len(source.splitlines())
    code = "\n".join(source.splitlines()[end:]).strip("\n")
    return title.strip().rstrip("."), body.strip(), code


def example_page(path):
    with open(path) as fh:
        source = fh.read()
    title, body, code = split_docstring(source)
    out = run_example(path)
    rel = os.path.relpath(path, REPO)
    return title, (
        "# %s\n\n%s\n\n" % (title, body)
        + "Source: [`%s`](%s/blob/main/%s), run as `python %s`.\n\n" % (rel, GITHUB, rel, rel)
        + fence("python", code)
        + "\nOutput, from running it when this page was built:\n\n"
        + fence("text", out)
        + "\n" + provenance())


# ---------------------------------------------------------------- API

PUBLIC_CLASSES = ("chunk2sparse", "chunk2sparseCSC")
PUBLIC_METHODS = ("__call__", "multi", "decode_offsets", "coo")


def signature(obj, name):
    try:
        return "%s%s" % (name, inspect.signature(obj))
    except (TypeError, ValueError):
        return name


def docblock(obj):
    doc = inspect.getdoc(obj)
    if not doc:
        raise SystemExit("%r has no docstring: write one in the code, not here"
                         % getattr(obj, "__qualname__", obj))
    return fence("text", doc)


def api_page():
    parts = ["# API reference\n",
             "Everything here is read from the installed module: the signatures by "
             "introspection, the text from the docstrings in `src/`.\n",
             "## The package\n", fence("text", inspect.getdoc(b))]
    for name in PUBLIC_CLASSES:
        cls = getattr(b, name)
        parts.append("## %s\n" % name)
        parts.append(fence("python", "class " + signature(cls, name)))
        parts.append(docblock(cls))
        for m in PUBLIC_METHODS:
            meth = getattr(cls, m)
            parts.append("### %s.%s\n" % (name, m))
            parts.append(fence("python", signature(meth, m)))
            parts.append(docblock(meth))
    funcs = [n for n in b.__all__ if n not in PUBLIC_CLASSES and callable(getattr(b, n))]
    for name in funcs:
        fn = getattr(b, name)
        parts.append("## %s\n" % name)
        parts.append(fence("python", signature(fn, name)))
        parts.append(docblock(fn))
    consts = [n for n in b.__all__ if not callable(getattr(b, n))]
    parts.append("## Constants\n")
    parts.append("| name | value |\n|---|---|\n"
                 + "".join("| `%s` | `%r` |\n" % (n, getattr(b, n)) for n in consts))
    parts.append("\n## Decode errors\n\nA negative return from the native decode is "
                 "raised as an `Exception` with this text (`_DECODE_ERRORS` in "
                 "`src/__init__.py`):\n\n| code | meaning |\n|---|---|\n"
                 + "".join("| %d | %s |\n" % (k, v) for k, v in sorted(b._DECODE_ERRORS.items(),
                                                                        reverse=True)))
    parts.append("\n" + provenance())
    return "\n".join(parts)


# ---------------------------------------------------------------- pipelines

def pipelines_page():
    parts = ["# Pipeline steps and values\n",
             "Every value of every step: what it does, from the comments in the C sources "
             "(linked), and what it needs, from `VALUES` in `src/_pipeline.py`.  Value 0 "
             "(`auto`) is resolved when an object is made; `describe()` shows which values "
             "the running machine can use (see the [pipelines example](examples/ex4_pipelines.md)), "
             "and the [kernel page](kernels.md) times them all.\n",
             step_values_section("##"), "\n" + provenance()]
    return "\n".join(parts)


# ---------------------------------------------------------------- performance

def bench_docs_py_sha256():
    """The hash tools/bench_docs.py records, of the module being documented."""
    sys.path.insert(0, os.path.join(REPO, "tools"))
    try:
        from bench_docs_hash import py_sha256
    finally:
        sys.path.pop(0)
    return py_sha256(os.path.dirname(b.__file__))


def bins_per_pixel(mi):
    if "bins_per_pixel_mean" not in mi:
        return ""
    return "%.2f, %d" % (mi["bins_per_pixel_mean"], mi["bins_per_pixel_max"])


def pct(frac):
    """A fraction as a percentage: two significant figures, whole numbers from 10 %."""
    p = 100 * frac
    return ("%.0f %%" % p) if p >= 10 else ("%.2g %%" % p)


def bench_files():
    """The committed measurements, one JSON per machine (tools/bench_docs.py)."""
    return sorted(glob.glob(BENCH_GLOB))


def cpu_label(cpu):
    """'Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz' -> 'Intel Xeon Gold 6248'."""
    for junk in ("(R)", "(TM)", "CPU", "Processor"):
        cpu = cpu.replace(junk, " ")
    cpu = re.sub(r"@.*$|\b\d+-Core\b", " ", cpu)
    return " ".join(cpu.split())


def stale_warning(bench, here, here_py):
    m = bench["machine"]
    if m["src_sha256"] == here and m.get("py_sha256") == here_py:
        return ""
    return ('!!! warning "%s: measured on older code"\n'
            "    Measured at git `%s` (C sources sha256 `%s`, kernel-choice modules `%s`); "
            "this site was built from `%s` / `%s`.  The code changed since, so these "
            "numbers may no longer describe it.  Re-run `tools/bench_docs.py` on that "
            "machine and commit its JSON.\n"
            % (cpu_label(m["cpu"]), m["git"], m["src_sha256"][:12],
               str(m.get("py_sha256"))[:12], here[:12], here_py[:12]))


def performance_page():
    benches = []
    for path in bench_files():
        with open(path) as fh:
            benches.append((os.path.relpath(path, REPO), json.load(fh)))
    ref = benches[0][1]                 # data, cases, method: the same in every file
    meth = ref["method"]
    here = b.build_info()["src_sha256"]
    here_py = bench_docs_py_sha256()
    parts = ["# Performance on real data"]
    parts += [w for w in (stale_warning(bm, here, here_py) for _, bm in benches) if w]
    parts.append(
        "Three real ID11 Eiger data sets, each decoded on **one core** of each machine "
        "below.  %d frames spread over each file were read into memory first (no file "
        "I/O is timed), then decoded in batches of %d after one warmup batch; the best "
        "of %d passes is shown.  GB = 10^9 bytes.  *Compressed* GB/s counts the "
        "bitshuffle-LZ4 bytes consumed, *pixels* GB/s the decompressed frame (pixels x "
        "bytes per pixel): their ratio is the compression ratio.  Pipelines are the "
        "automatic choice on each machine, from the same build.\n"
        % (meth["frames"], meth["batch"], meth["repeats"]))
    g = meth["geometry"]
    parts.append(
        "The files carry no calibration, so the matrices use one generic geometry for "
        "every case: %g um pixels, %g m distance, beam at the detector centre, "
        "wavelength %g m, no tilts.  They set the size and shape of the work, not a "
        "fit to these samples.  Masked pixels: %s.\n"
        % (g["pixel_m"] * 1e6, g["dist_m"], g["wavelength_m"], meth["mask"]))

    parts.append("## Machines")
    parts.append("| machine | measured (UTC) | build | compiler | "
                 "Python, numpy, pyFAI | data |\n|---|---|---|---|---|---|\n"
                 + "".join("| **%s** | %s | %s `%s` | %s | %s, %s, %s | [`%s`](%s/blob/main/%s) |\n"
                           % (cpu_label(bm["machine"]["cpu"]),
                              bm["date_utc"], bm["machine"]["version"], bm["machine"]["git"],
                              bm["machine"]["compiler"], bm["machine"]["python"],
                              bm["machine"]["numpy"], bm["machine"]["pyFAI"],
                              os.path.basename(path), GITHUB, path)
                           for path, bm in benches))

    parts.append("## Frames per second")
    table = ("| data set | operation | "
             + " | ".join(cpu_label(bm["machine"]["cpu"]) for _, bm in benches)
             + " |\n|---|---|" + "---:|" * len(benches) + "\n")
    op_order = []                                   # as measured (the JSON keys are sorted)
    for r in ref["results"]:
        if r["op"] not in op_order:
            op_order.append(r["op"])
    fps = {}
    for _, bm in benches:
        for r in bm["results"]:
            fps[(id(bm), r["case"], r["op"])] = r
    for case in ref["cases"]:
        for op in op_order:
            table += "| %s | %s | %s |\n" % (
                case["key"], op, " | ".join("%.1f" % fps[(id(bm), case["key"], op)]["fps"]
                                            for _, bm in benches))
    parts.append(table)

    parts.append("## Operations")
    parts.append("| operation | what is timed |\n|---|---|\n"
                 + "".join("| %s | %s |\n" % (op, ref["ops"][op]) for op in op_order))

    for case in ref["cases"]:
        rows = [r for r in ref["results"] if r["case"] == case["key"]]
        parts.append("## %s: %s\n" % (case["key"], case["label"]))
        parts.append("`%s`, dataset `%s`: %d frames of %s %s; compression %.1f; "
                     "%d masked pixels.  Sparse cut %d: %s of the unmasked pixels are "
                     "above it and go to the sparse output (mean over the timed frames).\n"
                     % (case["file"], case["dataset"], case["frames_in_file"],
                        " x ".join(str(s) for s in case["shape"]), case["dtype"],
                        case["compression"], case["masked_pixels"], case["cut"],
                        pct(case["kept_frac"])))
        mats = [r for r in rows if r["matrix"]]
        if mats:
            parts.append("| matrix | bins | entries | pixels with an entry | bins per pixel (mean, max) |\n"
                         "|---|---:|---:|---:|---:|\n"
                         + "".join("| %s | %s | %d | %s | %s |\n"
                                   % (r["op"], " x ".join(str(n) for n in r["matrix"]["bins_shape"]),
                                      r["matrix"]["nnz"], pct(r["matrix"]["pixel_frac"]),
                                      bins_per_pixel(r["matrix"]))
                                   for r in mats))
        table = ("| operation | machine | frames/s | compressed GB/s | pixels GB/s |\n"
                 "|---|---|---:|---:|---:|\n")
        for op in op_order:
            for _, bm in benches:
                r = fps[(id(bm), case["key"], op)]
                table += ("| %s | %s | %.1f | %.3f | %.2f |\n"
                          % (op, cpu_label(bm["machine"]["cpu"]), r["fps"],
                             r["compressed_gbs"], r["pixel_gbs"]))
        parts.append(table)
    parts.append("Written by `%s`; one JSON per machine in `docs/bench/`.\n\n"
                 % ref["tool"] + provenance())
    return "\n".join(p.rstrip("\n") + "\n" for p in parts)


# ---------------------------------------------------------------- acknowledgements

def md_section(text, heading):
    """The body of the '## heading' section of a Markdown text."""
    m = re.search(r"^## %s\n(.*?)(?=^## |\Z)" % re.escape(heading), text, re.M | re.S)
    if not m:
        raise SystemExit("README.md has no '## %s' section" % heading)
    return m.group(1).strip()


def acknowledgements_page():
    with open(os.path.join(REPO, "README.md")) as fh:
        readme = fh.read()
    with open(os.path.join(REPO, "licenses", "README.md")) as fh:
        lic = fh.read()
    # the component table of licenses/README.md, its file names linked
    table = "\n".join(l for l in lic.splitlines() if l.startswith("|"))
    table = re.sub(r"`([A-Z0-9-]+-LICENSE(?:-[A-Z]+)?)`",
                   lambda m: "[`%s`](%s/blob/main/licenses/%s)" % (m.group(1), GITHUB, m.group(1)),
                   table)
    parts = ["# Acknowledgements and licences",
             "From `README.md` and `licenses/` in the repository.",
             "## Acknowledgements", md_section(readme, "Acknowledgements"),
             "## References", md_section(readme, "References"),
             "## Licences",
             "bslz4_to_sparse is MIT licensed.  The compiled extension contains code "
             "from the projects below, built from the repository's git submodules; "
             "their licences ship in every wheel and sdist.",
             table]
    files = ["LICENSE"] + ["licenses/" + f for f in sorted(os.listdir(os.path.join(REPO, "licenses")))
                           if f != "README.md"]
    for rel in files:
        with open(os.path.join(REPO, rel)) as fh:
            parts.append("### %s" % ("bslz4_to_sparse (`LICENSE`)" if rel == "LICENSE"
                                      else "`%s`" % os.path.basename(rel)))
            parts.append(fence("text", fh.read()))
    parts.append(provenance())
    return "\n\n".join(p.rstrip("\n") for p in parts) + "\n"


# ---------------------------------------------------------------- step value docs

C_DOC_DIRS = ("src/steps", "src/pipeline")
_C_ENTRY = re.compile(r"^ \*   (BSLZ4_([A-Z]+)_[A-Z0-9_]+)( +)(\S.*)$")


def c_enum_values():
    """{enum constant: (step, value name)} from the step enums of pipeline.h."""
    with open(os.path.join(REPO, "src", "pipeline", "pipeline.h")) as fh:
        text = fh.read()
    out = {}
    for step in _pipeline.STEPS:
        for const, n in re.findall(r"\b(BSLZ4_%s_[A-Z0-9_]+)\s*=\s*(\d+)" % step.upper(), text):
            n = int(n)
            if 0 < n < len(_pipeline.NAMES[step]):
                out[const] = (step, _pipeline.NAMES[step][n])
    return out


def c_value_docs():
    """{step: {value name: (text, path, line)}} from the per-value comment blocks
    (' *   BSLZ4_STEP_VALUE  text', continuation lines indented to the text) in
    the C sources: the description of every pipeline step value."""
    consts = c_enum_values()
    docs = {s: {} for s in _pipeline.STEPS}
    for d in C_DOC_DIRS:
        for path in sorted(glob.glob(os.path.join(REPO, d, "*"))):
            with open(path) as fh:
                lines = fh.read().splitlines()
            i = 0
            while i < len(lines):
                m = _C_ENTRY.match(lines[i])
                if not m or m.group(1) not in consts:
                    i += 1
                    continue
                text, start = m.group(4).strip(), i + 1
                i += 1
                # continuation: indented deeper than the entry's constant
                while i < len(lines) and re.match(r"^ \*      +\S", lines[i]) \
                        and not _C_ENTRY.match(lines[i]):
                    more = lines[i][2:].strip()
                    text += more if text.endswith("_") else " " + more   # split identifier
                    i += 1
                step, name = consts[m.group(1)]
                docs[step][name] = (text, os.path.relpath(path, REPO), start)
    return docs


def step_values_section(heading="##"):
    """Every step value with its description from the C sources."""
    docs = c_value_docs()
    parts = []
    for step in _pipeline.STEPS:
        rows = ""
        for i, v in enumerate(_pipeline.VALUES[step]):
            if not i:
                continue
            name = _pipeline.NAMES[step][i]
            needs = v[1] if not isinstance(v, str) and len(v) > 1 else ""
            text, path, line = docs[step].get(name, ("", None, 0))
            src = "[%s:%d](%s/blob/main/%s#L%d)" % (os.path.basename(path), line, GITHUB, path,
                                                    line) if path else ""
            rows += "| `%s` | %s | %s | %s |\n" % (name, text.replace("|", "\\|"), needs, src)
        parts.append("%s %s\n\n| value | what it does | needs | source |\n|---|---|---|---|\n%s"
                     % (heading, step, rows))
    return "\n".join(parts)


# ---------------------------------------------------------------- kernels

KERNELS_GLOB = os.path.join(DOCS, "bench", "kernels_*.json")
SPARSIFY_STEPS = ("decode", "mask", "untranspose", "collect")


def kernel_check(r):
    """The correctness column: sparse output identical, powder difference."""
    txt = "same" if r["sparse_ok"] else "**differs**"
    if "powder_rel" in r:
        txt += "; powder %s" % ("exact" if r["powder_rel"] == 0 else "%.1e" % r["powder_rel"])
    return txt


def axis_tables(rows, base, note):
    """The automatic pipeline line and one table per step varied."""
    parts = ["Automatic pipeline: %s.  Each table varies one step, the others held "
             "there%s." % (", ".join("%s `%s`" % (k, base[k]) for k in _pipeline.STEPS if k in base),
                           note)]
    axes = []
    for r in rows:
        if r["axis"] not in axes:
            axes.append(r["axis"])
    for axis in axes:
        arows = [r for r in rows if r["axis"] == axis]
        table = ("| %s | frames/s | compressed GB/s | pixels GB/s | vs auto |\n"
                 "|---|---:|---:|---:|---|\n" % axis)
        for r in sorted([r for r in arows if "fps" in r], key=lambda r: -r["fps"]):
            is_auto = all(r["pipeline"].get(k) == base[k] for k in base)
            table += "| %s | %.1f | %.3f | %.2f | %s |\n" % (
                ("**`%s`**" if is_auto else "`%s`") % r["pipeline"].get(axis), r["fps"],
                r["compressed_gbs"], r["pixel_gbs"],
                ("**auto**; " if is_auto else "") + kernel_check(r))
        for r in arows:
            if "refused" in r:
                table += "| `%s` | refused: %s | | | |\n" % (
                    r["pipeline"].get(axis), r["refused"].replace("|", "\\|"))
        parts.append(table)
    return parts


def kernels_page():
    files = sorted(glob.glob(KERNELS_GLOB))
    parts = ["# Kernels: each pipeline step on real data"]
    if not files:
        parts.append("No measurement committed yet (`docs/bench/kernels_*.json`, "
                     "written by `tools/bench_kernels.py`).")
        return "\n\n".join(parts) + "\n"
    here = b.build_info()["src_sha256"]
    here_py = bench_docs_py_sha256()
    kms = []
    for path in files:
        with open(path) as fh:
            kms.append((path, json.load(fh)))
    anchor = lambda t: re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")
    parts.append(
        "The C code composes a pipeline at run time (a switch per step per decode "
        "block; templates only over the pixel type), so each step is timed on its own: "
        "starting from the automatic pipeline, each value of one step with the others "
        "held there.  Machines: %s; each has its own section after the description of "
        "the step values."
        % ", ".join("[%s](#%s)" % (cpu_label(km["machine"]["cpu"]),
                                    anchor(cpu_label(km["machine"]["cpu"]))) for _, km in kms))
    parts.append("## The pipeline steps\n\nWhat each value timed below does, from the "
                 "comments in the C sources (linked), and what it needs, from "
                 "`src/_pipeline.py`.")
    parts.append(step_values_section("###"))
    for path, km in kms:
        m, meth = km["machine"], km["method"]
        parts.append("## %s" % cpu_label(m["cpu"]))
        w = stale_warning(km, here, here_py)
        if w:
            parts.append(w)
        parts.append(
            "**One core of %s**, %s UTC, bslz4_to_sparse %s (git `%s`); the whole run took "
            "%s s.  %d frames spread over each file, re-encoded in memory with each codec "
            "and block size listed; one pass over all frames checks the result against the "
            "automatic pipeline and warms up, then the best of %d timed passes (batches of "
            "%d, no file I/O).  Sparsify is also timed *no mask*: %s.  **Bold** marks the "
            "automatic choice; *vs auto*: the sparse output must be the same, the powder is "
            "compared as max |difference| / max |powder| (the fixed-point dots round).  "
            "Values the library refuses for the data, block size or matrix are listed with "
            "the reason."
            % (cpu_label(m["cpu"]), km["date_utc"], m["version"], m["git"],
               meth.get("seconds", "?"), meth["frames"], meth["repeats"], meth["batch"],
               meth["no_mask"]))
        parts.append(
            "The matrices (one generic geometry, %s pixels; the kevlar frames are cropped "
            "to it, and every object folds its own data set's mask):\n\n"
            "| matrix | what | bins | entries | pixels with an entry | bins per pixel (mean, max) |\n"
            "|---|---|---:|---:|---:|---:|\n" % " x ".join(str(x) for x in meth["shape"])
            + "".join("| %s | %s | %s | %d | %s | %s |\n"
                      % (op, km["ops"][op], " x ".join(str(n) for n in mi["bins_shape"]),
                         mi["nnz"], pct(mi["pixel_frac"]), bins_per_pixel(mi))
                      for op, mi in km["matrices"].items()))
        for ds in km["datasets"]:
            parts.append("### %s: %s" % (ds["key"], ds["label"]))
            parts.append(
                "`%s` (%s, %s %s, %d masked pixels, cut %d).  Encodings:\n\n"
                "| encoding | codec | level | block | compression | tables |\n"
                "|---|---|---|---:|---:|---|\n"
                % (ds["file"], ds["dataset"], " x ".join(str(x) for x in ds["shape"]),
                   ds["dtype"], ds["masked_pixels"], ds["cut"])
                + "".join("| %s | %s | %s | %d kB | %.1f | %s |\n"
                          % (e["key"], e["codec"], e["clevel"] if e["clevel"] else "-",
                             e["block_bytes"] // 1024, e["compression"],
                             "sparsify, matrices" if e["key"] in ds["matrix_encodings"]
                             else "sparsify")
                          for e in ds["encodings"]))
            for e in ds["encodings"]:
                auto = km["auto"][ds["key"]][e["key"]]
                kinds = []
                for r in km["results"]:            # in the order measured
                    if r["data"] == ds["key"] and r["variant"] == e["key"] and r["kind"] not in kinds:
                        kinds.append(r["kind"])
                for kind in kinds:
                    rows = [r for r in km["results"] if r["data"] == ds["key"]
                            and r["variant"] == e["key"] and r["kind"] == kind]
                    sp = kind.startswith("sparsify")
                    parts.append("#### %s, %s, %s" % (ds["key"], e["key"],
                                                      kind if sp else kind + " matrix"))
                    parts += axis_tables(rows, auto[kind],
                                         " (the collect table holds untranspose `kcb`: the "
                                         "low-planes values fuse the collect)" if sp else "")
        parts.append("Source: `%s`, written by `%s`." % (os.path.relpath(path, REPO), km["tool"]))
    parts.append(provenance())
    return "\n\n".join(p.rstrip("\n") for p in parts) + "\n"


def main():
    write("api.md", api_page())
    write("pipelines.md", pipelines_page())
    write("kernels.md", kernels_page())
    write("acknowledgements.md", acknowledgements_page())
    write("performance.md", performance_page())
    for path in examples():
        name = os.path.splitext(os.path.basename(path))[0]
        _title, page = example_page(path)
        write(os.path.join("examples", name + ".md"), page)


if __name__ == "__main__":
    main()
