#!/usr/bin/env python3
"""
Regenerate src/bslz4_to_sparse_wrapper.c from the C2PY_BEGIN block in
src/bslz4_to_sparse.cpp.

This is a developer-only tool, run by hand after editing that spec (new
dtype, new function, changed signature, ...). The generated wrapper is
committed to the repo precisely so that c2py23 is NOT needed to build or
install this package day to day -- only to regenerate it when the spec
actually changes. If the spec hasn't changed, the wrapper doesn't need
regenerating either.

Requires c2py23 installed (`pip install c2py23`, or point PYTHONPATH at a
local checkout). After running this, update the commit-hash comment near
the top of the regenerated file to record which c2py23 checkout produced
it, and re-run the test suite before committing.
"""
import os
import subprocess
import sys

import c2py23
from c2py23.generator import generate
from c2py23.harvester import extract_from_file
from c2py23.parser import from_c2py_dict

HERE = os.path.abspath(os.path.dirname(__file__))
REPO_ROOT = os.path.dirname(HERE)


def c2py23_commit():
    try:
        return (
            subprocess.check_output(
                ["git", "-C", os.path.dirname(c2py23.__file__), "rev-parse", "HEAD"]
            )
            .decode()
            .strip()
        )
    except Exception:
        return None


def main():
    source_path = os.path.join(REPO_ROOT, "src", "bslz4_to_sparse.cpp")
    wrapper_path = os.path.join(REPO_ROOT, "src", "bslz4_to_sparse_wrapper.c")

    spec = extract_from_file(source_path)
    module = from_c2py_dict(spec, source_path)
    code = generate(module)

    commit = c2py23_commit()
    banner = "/* Generated by c2py23 v%s - do not edit by hand\n" % c2py23.__version__
    banner += " *\n * Generated from and committed against:\n"
    if commit:
        banner += " *   %s\n" % commit
    else:
        banner += " *   (unknown checkout -- pass a git checkout of c2py23, not a wheel)\n"
    banner += (
        " *\n"
        " * This file is committed to the repo so building bslz4_to_sparse does\n"
        " * not require c2py23 to be installed (see c2py_runtime/README.md).\n"
        " * Regenerate with tools/regenerate_wrapper.py after changing the\n"
        " * C2PY_BEGIN spec in src/bslz4_to_sparse.cpp, and update the commit\n"
        " * hash above to whichever c2py23 checkout produced the new output.\n"
        " */\n"
    )
    # generate() emits its own one-line banner as the first line; replace it.
    lines = code.splitlines(keepends=True)
    if lines and lines[0].startswith("/* Generated by c2py23"):
        code = banner + "".join(lines[1:])
    else:
        code = banner + code

    with open(wrapper_path, "w") as f:
        f.write(code)
    print("wrote %s (%d lines)" % (wrapper_path, len(code.splitlines())))
    if not commit:
        print(
            "WARNING: could not determine the c2py23 git commit -- edit the "
            "banner in %s by hand before committing." % wrapper_path,
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
