import struct
import numpy as np
import ctypes
from . import bslz4_to_sparse as _ext
from .bslz4_to_sparse import bslz4, bslz4_csc, bslz4_csc_multi, bslz4_csc_multi_base, note_chunk
from .bslz4_to_sparse import (
    _rebind_bslz4,
    _rebind_bslz4_csc,
    _rebind_bslz4_csc_multi,
    _rebind_bslz4_csc_multi_base,
    _variants_bslz4,
)

version = "0.1.0"

# c2py23's per-call timing instrumentation is compiled in (useful together
# with set_backend() for benchmarking kernels against each other) but kept
# off by default so ordinary decoding pays no timing overhead.
_ext._c2py_perf_set_enabled(0)


def set_timing(enabled):
    """Enable/disable c2py23's per-call timing instrumentation (off by default)."""
    _ext._c2py_perf_set_enabled(1 if enabled else 0)

# We cast away the 'read-only' nature of python bytes.
# Not needed for the latest numpy.
if hasattr( ctypes.pythonapi, "PyMemoryView_FromMemory"):
    buffer_from_memory = ctypes.pythonapi.PyMemoryView_FromMemory
    buffer_from_memory.restype = ctypes.py_object
    buffer_from_memory.argtypes = (ctypes.c_void_p, ctypes.c_int, ctypes.c_int)
else:
    def buffer_from_memory(buf, l, f):
        if type(buf) == str and buf[:6] == 'array(':
            # python 2.7 and a rather sad feature in h5py.
            #   probably we should not support this.
            import warnings
            warnings.warn('Bad performance from python2.7 and old h5py')
            from array import array
            return eval(buf)
        raise Exception('Unknown code path for buffer decoding ' + str(type(buf)))


def npbuf(buf):
    if isinstance(buf, np.ndarray):
        return buf
    elif isinstance(buf, memoryview):
        return np.frombuffer(buf, np.uint8)
    else:
        return np.frombuffer(buffer_from_memory(buf, len(buf), 0x200), np.uint8)


# Pixel type suffixes for the per-type dispatch groups generated by c2py23
# (see the C2PY_BEGIN block in src/bslz4_to_sparse.cpp).
_TYPE_SUFFIXES = ("u8", "u16", "u32", "i8", "i16", "i32", "f32", "f64")

DEFAULT_BLOCK_BYTES = 8192

# bitshuffle-hdf5 filter id and its cd_values[4] block-codec numbering
# (bitshuffle/src/bshuf_h5filter.h: BSHUF_H5_COMPRESS_LZ4/_ZSTD).
BSHUF_H5FILTER = 32008
CODEC_LZ4 = 2
CODEC_ZSTD = 3


def detect_codec(ds):
    """
    Detect which block codec (CODEC_LZ4 or CODEC_ZSTD) a dataset's
    bitshuffle filter was configured with, from its HDF5 filter pipeline
    (cd_values[4]). Falls back to CODEC_LZ4 if it can't be determined
    (e.g. no bitshuffle filter present).
    """
    try:
        plist = ds.id.get_create_plist()
        for i in range(plist.get_nfilters()):
            filter_id, _flags, cd_values, _name = plist.get_filter(i)
            if filter_id == BSHUF_H5FILTER and len(cd_values) > 4:
                return cd_values[4]
    except Exception:
        pass
    return CODEC_LZ4


def _blocksize_bytes(cmp):
    """
    The bitshuffle block size (bytes) encoded in this compressed chunk's
    stream header (bytes 8:12, big endian; 0 means the 8192 byte default).

    Works on any buffer-protocol object whose integer indexing returns
    ints (bytes/bytearray/memoryview/numpy uint8 array on Python 3;
    plain bytes/str indexing on Python 2.7 needs bytearray(cmp[8:12])
    instead -- not handled here yet, see _gather_chunks).
    """
    if len(cmp) < 12:
        return DEFAULT_BLOCK_BYTES
    blocksize = (int(cmp[8]) << 24) | (int(cmp[9]) << 16) | (int(cmp[10]) << 8) | int(cmp[11])
    return blocksize if blocksize else DEFAULT_BLOCK_BYTES


def _gather_chunks(chunks):
    """
    Build the (pointers, lengths) pair bslz4_csc_multi expects from a
    plain Python sequence of independent chunk buffers (bytes, bytearray,
    memoryview, mmap slices, ... any buffer-protocol object -- source
    type doesn't matter and isn't inspected).

    No numpy, no ctypes, no array module: pointers/lengths are plain
    bytearrays (int64/int32 little-endian each), and note_chunk (a
    genuine c2py23-wrapped function, so it's c2py23's own buffer
    acquisition doing the address extraction, not a Python-side
    reimplementation of it) writes each chunk's address+length into
    them directly. The `chunks` list itself is consumed entirely here in
    Python -- c2py23 never sees more than one buffer object per call.
    """
    n = len(chunks)
    pointers = bytearray(n * 8)
    lengths = bytearray(n * 4)
    for i, chunk in enumerate(chunks):
        note_chunk(chunk, i, pointers, lengths)
    return pointers, lengths


def harvest_chunk_offsets(ds):
    """
    Harvest {frame_index: (byte_offset, byte_size)} for every stored
    chunk of a (1, ni, nj)-chunked bitshuffle dataset, via h5py's
    chunk_iter (h5py >=3.8: one native B-tree traversal) or, if that's
    not available, a get_num_chunks()/get_chunk_info() loop.

    Raises ValueError if ds isn't chunked (1, ni, nj) -- 4-D (1,1,ni,nj)
    chunking is not supported yet -- or if any chunk has the bitshuffle
    filter (pipeline position 0) marked skipped in its filter_mask (that
    chunk's bytes would be raw pixel data, not a bitshuffle stream; in
    practice this doesn't happen for these datasets, so it's a hard
    error here rather than a case decode needs to handle).
    """
    chunks = tuple(ds.chunks) if ds.chunks is not None else None
    if chunks is None or len(chunks) != 3 or chunks[0] != 1:
        raise ValueError(
            "harvest_chunk_offsets needs a (1, ni, nj)-chunked dataset, got chunks=%r "
            "(4-D (1,1,ni,nj) chunking is not supported yet)" % (chunks,)
        )

    offsets = {}

    def _store(frame, byte_offset, byte_size, filter_mask):
        if filter_mask & 1:
            raise ValueError(
                "chunk for frame %d has the bitshuffle filter skipped (filter_mask=%d); "
                "raw (uncompressed) chunk passthrough is not supported" % (frame, filter_mask)
            )
        offsets[frame] = (byte_offset, byte_size)

    if hasattr(ds.id, "chunk_iter"):
        def _cb(chunk_info):
            _store(chunk_info.chunk_offset[0], chunk_info.byte_offset,
                   chunk_info.size, chunk_info.filter_mask)
            # must not return 0 (or any falsy-to-HDF5-iterator value that
            # h5py maps to H5_ITER_STOP) -- returning None continues.
        ds.id.chunk_iter(_cb)
    else:
        for i in range(ds.id.get_num_chunks()):
            info = ds.id.get_chunk_info(i)
            _store(info.chunk_offset[0], info.byte_offset, info.size, info.filter_mask)

    return offsets


def pack_offsets_lengths(frame_offsets, frames):
    """
    Build the (offsets, lengths) pair bslz4_csc_multi_base expects, from
    harvest_chunk_offsets()'s {frame_index: (byte_offset, byte_size)}
    result and the ordered list of frame indices to include. Plain
    bytearrays filled via struct.pack_into -- these are byte offsets,
    already plain Python ints from HDF5 metadata, so no buffer-address
    extraction (note_chunk) is needed here at all.
    """
    n = len(frames)
    offsets = bytearray(n * 8)
    lengths = bytearray(n * 4)
    for i, frame in enumerate(frames):
        byte_offset, byte_size = frame_offsets[frame]
        struct.pack_into("<q", offsets, i * 8, byte_offset)
        struct.pack_into("<i", lengths, i * 4, byte_size)
    return offsets, lengths


def _workspace_bytes(cmp):
    """
    Bytes required for the single-frame decode workspace for this
    compressed chunk: 3 times its block size (see _blocksize_bytes).
    """
    return 3 * _blocksize_bytes(cmp)


def _workspace_bytes_multi(cmp, nframes):
    """
    Bytes required for the bslz4_csc_multi decode workspace: (nframes + 2)
    times the block size (see bslz4_core.hpp -- one untransposed-block
    region per frame, plus one shared raw + one shared scratch region).
    """
    return (nframes + 2) * _blocksize_bytes(cmp)


def available_backends():
    """
    Names of the untranspose backends compiled into this build (e.g.
    'kcb', 'scal'). See set_backend().
    """
    names = [v.decode() for v in _variants_bslz4()]
    return tuple(sorted(set(name.rsplit("_", 1)[-1] for name in names)))


def set_backend(name):
    """
    Select which untranspose (bit/byte de-shuffle) backend bslz4_to_sparse
    uses. 'kcb' (https://github.com/kalcutter/bitshuffle) is the default
    and does its own CPU dispatch; 'scal' is the portable reference kernel
    from upstream bitshuffle (https://github.com/kiyo-masui/bitshuffle).
    See available_backends() for the names compiled into this build.

    Applies to every pixel type and to both the plain and CSC decoders,
    so the kernels can be measured against each other rather than one
    being silently fixed at build time. Pass None to restore auto-resolve.
    """
    for suffix in _TYPE_SUFFIXES:
        _rebind_bslz4(None if name is None else "bslz4_%s_%s" % (suffix, name))
        _rebind_bslz4_csc(None if name is None else "bslz4_csc_%s_%s" % (suffix, name))
        _rebind_bslz4_csc_multi(
            None if name is None else "bslz4_csc_multi_%s_%s" % (suffix, name)
        )
        _rebind_bslz4_csc_multi_base(
            None if name is None else "bslz4_csc_multi_base_%s_%s" % (suffix, name)
        )


class chunk2sparse:
    def __init__(self, mask, dtype=np.uint16, codec=CODEC_LZ4):
        self.nfast = mask.shape[1]
        self.mask = mask.ravel()
        self.indices = np.empty(mask.size, np.uint32)
        self.values = np.empty(mask.size, dtype)
        self.workspace = np.empty(3 * DEFAULT_BLOCK_BYTES, np.uint8)
        self.codec = codec

    def __call__(self, buffer, cut):
        buf = npbuf(buffer)
        need = _workspace_bytes(buf)
        if self.workspace.size < need:
            self.workspace = np.empty(need, np.uint8)
        npixels = bslz4(buf, self.mask, self.values, self.indices, self.workspace, cut, self.codec)
        return npixels, (self.values, self.indices)

    def coo(self, buffer, cut):
        """Computes i,j indices and MAKES COPIES"""
        npixels, _ = self.__call__(buffer, cut)
        row = np.empty(npixels, np.uint16)
        col = np.empty(npixels, np.uint16)
        np.divmod(self.indices[:npixels], self.nfast, out=(row, col))
        return npixels, row, col, self.values[:npixels].copy()


def bslz4_to_sparse(ds, num, cut, mask=None, pixelbuffer=None, workspace=None, codec=None):
    """
    Reads a bitshuffle compressed hdf5 dataset and converts this
    directly into a sparse format (indices, values) when decoding
    the data.

    ds = hdf5 dataset containing [nframes, ni, nj] pixels
    num = frame number to read
    cut = threshold, pixels below this value are ignored
    mask = detector mask. Active pixels > 0.
    pixelbuffer = None or (values, indices) storage space
    workspace = None or a uint8 array to use as decode scratch space
                (see _workspace_bytes / available_backends)
    codec = None to auto-detect lz4 vs zstd from ds's filter pipeline
            (see detect_codec), or an explicit CODEC_LZ4 / CODEC_ZSTD

    returns (number_of_pixels, (values, indices))
    """
    if mask is None:
        mask = np.ones((ds.shape[1], ds.shape[2]), np.uint8).ravel()
    if pixelbuffer is None:
        indices = np.empty((ds.shape[1], ds.shape[2]), np.uint32).ravel()
        values = np.empty((ds.shape[1], ds.shape[2]), ds.dtype).ravel()
    else:
        values, indices = pixelbuffer
    if codec is None:
        codec = detect_codec(ds)
    # todo : h5py malloc free version coming? see https://github.com/h5py/h5py/pull/2232
    filtinfo, buffer = ds.id.read_direct_chunk((num, 0, 0))
    #
    # h5py returns a bytes object that is read only. Older versions of numpy insist
    # to make a copy. We work around that using ctypes to set a writeable flag.
    #                                                      PyBUF_WRITE 0x200
    buf = npbuf(buffer)
    if workspace is None:
        workspace = np.empty(_workspace_bytes(buf), np.uint8)
    npixels = bslz4(buf, mask, values, indices, workspace, cut, codec)
    if npixels < 0:
        raise Exception("Error decoding: %d" % (npixels))
    return npixels, (values, indices)


class chunk2sparseCSC:
    def __init__(self, mask, csc, dtype=np.uint16, codec=CODEC_LZ4):
        """
        mask = detector mask
        csc = Either scipy.sparse.csc_matrix (data, indices, indptr, shape)
              Or  pyFAI CSCIntegrator object (data, indices, indptr, bins)
        dtype = the dtype for the pixels in the dataset
        codec = CODEC_LZ4 (default) or CODEC_ZSTD, matching the dataset's
                bitshuffle filter (see detect_codec)
        """
        self.nfast = mask.shape[1]  # used for coo function
        self.mask = mask.ravel()
        # for the csc product
        self.cscdata = csc.data
        self.cscindices = csc.indices
        self.cscindptr = csc.indptr
        assert len(csc.indptr) == len(self.mask) + 1, "csc shape must match mask"
        if hasattr(csc, "shape"):
            self.powder = np.empty(csc.shape[0], dtype=float)
        elif hasattr(csc, "bins"):
            self.powder = np.empty(csc.bins, dtype=float)
        else:
            raise Exception("csc argument has no shape or bins attribute")

        self.indices = np.empty(mask.size, np.uint32)
        self.values = np.empty(mask.size, dtype)
        self.workspace = np.empty(3 * DEFAULT_BLOCK_BYTES, np.uint8)
        self.codec = codec

    def __call__(self, buffer, cut):
        """
        Decompress buffer and place pixels above cut into (vals, indices)
        All pixels go into a powder integration (csc product)

        returns npixels, (values[fullsize], indices[fullsize]), powder_sum

        You will need to slice the result values[:npixels] yourself if you need that.
        """
        buf = npbuf(buffer)
        need = _workspace_bytes(buf)
        if self.workspace.size < need:
            self.workspace = np.empty(need, np.uint8)
        npixels = bslz4_csc(
            buf,
            self.mask,
            self.values,
            self.indices,
            cut,
            self.powder,
            self.cscdata,
            self.cscindices,
            self.cscindptr,
            self.workspace,
            self.codec,
        )
        return npixels, (self.values, self.indices), self.powder

    def coo(self, buffer, cut):
        """Computes i,j indices and MAKES COPIES"""
        npixels, _ = self.__call__(buffer, cut)
        row = np.empty(npixels, np.uint16)
        col = np.empty(npixels, np.uint16)
        np.divmod(self.indices[:npixels], self.nfast, out=(row, col))
        return npixels, row, col, self.values[:npixels].copy(), self.powder.copy()


class chunk2sparseCSCmulti:
    """
    Batched version of chunk2sparseCSC (issue #12): decodes a series of
    frames from the same dataset in one call. The CSC matrix (data,
    indices, indptr) lookup for each pixel is done once and applied
    across every frame's value for that pixel (instead of being re-walked
    once per frame), which is where the speedup over one chunk2sparseCSC
    call per frame comes from -- see bslz4_core.hpp's
    bslz4_csc_decode_multi for the loop restructuring this relies on.

    All frames must come from the same dataset (same detector shape/
    dtype/block size); chunk2sparseCSC's single-frame call still exists
    and is what this sits on top of in C.
    """

    def __init__(self, mask, csc, dtype=np.uint16, codec=CODEC_LZ4):
        """
        mask = detector mask
        csc = Either scipy.sparse.csc_matrix (data, indices, indptr, shape)
              Or  pyFAI CSCIntegrator object (data, indices, indptr, bins)
        dtype = the dtype for the pixels in the dataset
        codec = CODEC_LZ4 (default) or CODEC_ZSTD, matching the dataset's
                bitshuffle filter (see detect_codec)
        """
        self.nfast = mask.shape[1]
        self.mask = mask.ravel()
        self.cscdata = csc.data
        self.cscindices = csc.indices
        self.cscindptr = csc.indptr
        assert len(csc.indptr) == len(self.mask) + 1, "csc shape must match mask"
        if hasattr(csc, "shape"):
            self.nbins = csc.shape[0]
        elif hasattr(csc, "bins"):
            self.nbins = csc.bins
        else:
            raise Exception("csc argument has no shape or bins attribute")

        self.npix = mask.size
        self.dtype = dtype
        self.codec = codec

        self._nframes = 0
        self._outpx = None
        self._output_adr = None
        self._npx_out = None
        self._powder = None
        self._cursors = None
        self._workspace = None

    def _ensure_capacity(self, nframes, blocksize):
        if self._nframes != nframes:
            self._outpx = np.empty((nframes, self.npix), self.dtype)
            self._output_adr = np.empty((nframes, self.npix), np.uint32)
            self._npx_out = np.empty(nframes, np.int32)
            self._powder = np.empty((nframes, self.nbins), np.float64)
            self._cursors = np.empty(nframes, np.int64)
            self._nframes = nframes
        need = (nframes + 2) * blocksize
        if self._workspace is None or self._workspace.size < need:
            self._workspace = np.empty(need, np.uint8)

    def __call__(self, buffers, cut):
        """
        buffers = a sequence of N raw compressed chunks (one per frame,
                  e.g. from repeated ds.id.read_direct_chunk() calls),
                  all from the same dataset.
        cut = threshold, pixels below this value are ignored

        returns (npx_out, (outpx, output_adr), powder):
          npx_out      -- int32 array, length N, pixel count per frame
          outpx         -- (N, npix) array, outpx[f, :npx_out[f]] valid
          output_adr    -- (N, npix) uint32 array, same slicing
          powder        -- (N, nbins) float64 array, one full CSC
                            integration per frame

        The returned arrays are owned by this object and reused (and
        possibly reallocated) on the next call, exactly like
        chunk2sparseCSC's single-frame buffers.
        """
        nframes = len(buffers)
        blocksize = _blocksize_bytes(npbuf(buffers[0]))
        self._ensure_capacity(nframes, blocksize)

        pointers, lengths = _gather_chunks(buffers)

        ret = bslz4_csc_multi(
            pointers,
            lengths,
            nframes,
            self.mask,
            self._outpx.ravel(),
            self._output_adr.ravel(),
            self._npx_out,
            cut,
            self._powder.ravel(),
            self.cscdata,
            self.cscindices,
            self.cscindptr,
            self._workspace,
            self._cursors,
            self.nbins,
            self.codec,
        )
        if ret < 0:
            raise Exception("Error decoding batch: %d" % (ret))
        return self._npx_out, (self._outpx, self._output_adr), self._powder
