import numpy as np
import ctypes
from . import bslz4_to_sparse as _ext
from .bslz4_to_sparse import bslz4, bslz4_csc
from .bslz4_to_sparse import _rebind_bslz4, _rebind_bslz4_csc, _variants_bslz4

version = "0.1.0"

# c2py23's per-call timing instrumentation is compiled in (useful together
# with set_backend() for benchmarking kernels against each other) but kept
# off by default so ordinary decoding pays no timing overhead.
_ext._c2py_perf_set_enabled(0)


def set_timing(enabled):
    """Enable/disable c2py23's per-call timing instrumentation (off by default)."""
    _ext._c2py_perf_set_enabled(1 if enabled else 0)

# We cast away the 'read-only' nature of python bytes.
# Not needed for the latest numpy.
if hasattr( ctypes.pythonapi, "PyMemoryView_FromMemory"):
    buffer_from_memory = ctypes.pythonapi.PyMemoryView_FromMemory
    buffer_from_memory.restype = ctypes.py_object
    buffer_from_memory.argtypes = (ctypes.c_void_p, ctypes.c_int, ctypes.c_int)
else:
    def buffer_from_memory(buf, l, f):
        if type(buf) == str and buf[:6] == 'array(':
            # python 2.7 and a rather sad feature in h5py.
            #   probably we should not support this.
            import warnings
            warnings.warn('Bad performance from python2.7 and old h5py')
            from array import array
            return eval(buf)
        raise Exception('Unknown code path for buffer decoding ' + str(type(buf)))


def npbuf(buf):
    if isinstance(buf, np.ndarray):
        return buf
    elif isinstance(buf, memoryview):
        return np.frombuffer(buf, np.uint8)
    else:
        return np.frombuffer(buffer_from_memory(buf, len(buf), 0x200), np.uint8)


# Pixel type suffixes for the per-type dispatch groups generated by c2py23
# (see the C2PY_BEGIN block in src/bslz4_to_sparse.cpp).
_TYPE_SUFFIXES = ("u8", "u16", "u32")

DEFAULT_BLOCK_BYTES = 8192


def _workspace_bytes(cmp):
    """
    Bytes required for the bitshuffle-lz4 decode workspace for this
    compressed chunk: 3 times the block size encoded in the stream header
    (bytes 8:12, big endian; 0 means the 8192 byte default).
    """
    if cmp.size < 12:
        return 3 * DEFAULT_BLOCK_BYTES
    blocksize = (int(cmp[8]) << 24) | (int(cmp[9]) << 16) | (int(cmp[10]) << 8) | int(cmp[11])
    if blocksize == 0:
        blocksize = DEFAULT_BLOCK_BYTES
    return 3 * blocksize


def available_backends():
    """
    Names of the untranspose backends compiled into this build (e.g.
    'kcb', 'scal'). See set_backend().
    """
    names = [v.decode() for v in _variants_bslz4()]
    return tuple(sorted(set(name.rsplit("_", 1)[-1] for name in names)))


def set_backend(name):
    """
    Select which untranspose (bit/byte de-shuffle) backend bslz4_to_sparse
    uses. 'kcb' (https://github.com/kalcutter/bitshuffle) is the default
    and does its own CPU dispatch; 'scal' is the portable reference kernel
    from upstream bitshuffle (https://github.com/kiyo-masui/bitshuffle).
    See available_backends() for the names compiled into this build.

    Applies to every pixel type and to both the plain and CSC decoders,
    so the kernels can be measured against each other rather than one
    being silently fixed at build time. Pass None to restore auto-resolve.
    """
    for suffix in _TYPE_SUFFIXES:
        _rebind_bslz4(None if name is None else "bslz4_%s_%s" % (suffix, name))
        _rebind_bslz4_csc(None if name is None else "bslz4_csc_%s_%s" % (suffix, name))


class chunk2sparse:
    def __init__(self, mask, dtype=np.uint16):
        self.nfast = mask.shape[1]
        self.mask = mask.ravel()
        self.indices = np.empty(mask.size, np.uint32)
        self.values = np.empty(mask.size, dtype)
        self.workspace = np.empty(3 * DEFAULT_BLOCK_BYTES, np.uint8)

    def __call__(self, buffer, cut):
        buf = npbuf(buffer)
        need = _workspace_bytes(buf)
        if self.workspace.size < need:
            self.workspace = np.empty(need, np.uint8)
        npixels = bslz4(buf, self.mask, self.values, self.indices, self.workspace, cut)
        return npixels, (self.values, self.indices)

    def coo(self, buffer, cut):
        """Computes i,j indices and MAKES COPIES"""
        npixels, _ = self.__call__(buffer, cut)
        row = np.empty(npixels, np.uint16)
        col = np.empty(npixels, np.uint16)
        np.divmod(self.indices[:npixels], self.nfast, out=(row, col))
        return npixels, row, col, self.values[:npixels].copy()


def bslz4_to_sparse(ds, num, cut, mask=None, pixelbuffer=None, workspace=None):
    """
    Reads a bitshuffle compressed hdf5 dataset and converts this
    directly into a sparse format (indices, values) when decoding
    the data.

    ds = hdf5 dataset containing [nframes, ni, nj] pixels
    num = frame number to read
    cut = threshold, pixels below this value are ignored
    mask = detector mask. Active pixels > 0.
    pixelbuffer = None or (values, indices) storage space
    workspace = None or a uint8 array to use as decode scratch space
                (see _workspace_bytes / available_backends)

    returns (number_of_pixels, (values, indices))
    """
    if mask is None:
        mask = np.ones((ds.shape[1], ds.shape[2]), np.uint8).ravel()
    if pixelbuffer is None:
        indices = np.empty((ds.shape[1], ds.shape[2]), np.uint32).ravel()
        values = np.empty((ds.shape[1], ds.shape[2]), ds.dtype).ravel()
    else:
        values, indices = pixelbuffer
    # todo : h5py malloc free version coming? see https://github.com/h5py/h5py/pull/2232
    filtinfo, buffer = ds.id.read_direct_chunk((num, 0, 0))
    #
    # h5py returns a bytes object that is read only. Older versions of numpy insist
    # to make a copy. We work around that using ctypes to set a writeable flag.
    #                                                      PyBUF_WRITE 0x200
    buf = npbuf(buffer)
    if workspace is None:
        workspace = np.empty(_workspace_bytes(buf), np.uint8)
    npixels = bslz4(buf, mask, values, indices, workspace, cut)
    if npixels < 0:
        raise Exception("Error decoding: %d" % (npixels))
    return npixels, (values, indices)


class chunk2sparseCSC:
    def __init__(self, mask, csc, dtype=np.uint16):
        """
        mask = detector mask
        csc = Either scipy.sparse.csc_matrix (data, indices, indptr, shape)
              Or  pyFAI CSCIntegrator object (data, indices, indptr, bins)
        dtype = the dtype for the pixels in the dataset
        """
        self.nfast = mask.shape[1]  # used for coo function
        self.mask = mask.ravel()
        # for the csc product
        self.cscdata = csc.data
        self.cscindices = csc.indices
        self.cscindptr = csc.indptr
        assert len(csc.indptr) == len(self.mask) + 1, "csc shape must match mask"
        if hasattr(csc, "shape"):
            self.powder = np.empty(csc.shape[0], dtype=float)
        elif hasattr(csc, "bins"):
            self.powder = np.empty(csc.bins, dtype=float)
        else:
            raise Exception("csc argument has no shape or bins attribute")

        self.indices = np.empty(mask.size, np.uint32)
        self.values = np.empty(mask.size, dtype)
        self.workspace = np.empty(3 * DEFAULT_BLOCK_BYTES, np.uint8)

    def __call__(self, buffer, cut):
        """
        Decompress buffer and place pixels above cut into (vals, indices)
        All pixels go into a powder integration (csc product)

        returns npixels, (values[fullsize], indices[fullsize]), powder_sum

        You will need to slice the result values[:npixels] yourself if you need that.
        """
        buf = npbuf(buffer)
        need = _workspace_bytes(buf)
        if self.workspace.size < need:
            self.workspace = np.empty(need, np.uint8)
        npixels = bslz4_csc(
            buf,
            self.mask,
            self.values,
            self.indices,
            cut,
            self.powder,
            self.cscdata,
            self.cscindices,
            self.cscindptr,
            self.workspace,
        )
        return npixels, (self.values, self.indices), self.powder

    def coo(self, buffer, cut):
        """Computes i,j indices and MAKES COPIES"""
        npixels, _ = self.__call__(buffer, cut)
        row = np.empty(npixels, np.uint16)
        col = np.empty(npixels, np.uint16)
        np.divmod(self.indices[:npixels], self.nfast, out=(row, col))
        return npixels, row, col, self.values[:npixels].copy(), self.powder.copy()
